### PR TITLE
A temporary fix to sentence splitter behavior in TokenizerStateMachine when dealing with acronyms; Also fixing tokenizer unit tests to ensure test passing when using windows style line separator

### LINKED ISSUE #657: StatefulTokenizer error: lower case acronym ending with dot
The sentence "I was born in Urbana, IL. in 1992." is correctly recognized, but "I was born in Urbana, Il. in 1992." (IL with L in lower case) is split into two sentences.

### PR DESCRIPTION
**Pull request by schen149**
Adding a rule in [TokenizerStateMachine](https://github.com/CogComp/cogcomp-nlp/blob/master/tokenizer/src/main/java/edu/illinois/cs/cogcomp/nlp/tokenizer/TokenizerStateMachine.java) -- When the current character is a period; the next char is white space; and the next next char is a lower-cased alphabet, (I think) we can safely say that the next word would not be the start of a sentence, so the TSM should not split on the current period.  

This fix resolves #657, but doesn't work on the last example Daniel mentioned in #492. 

> " A Science Hall was built in 1883 under the direction of Fr. Zahm, but in 1950 it was converted to a student union building and named LaFortune Center, after Joseph LaFortune, an oil executive from Tulsa, Oklahoma."

Also fixed tokenizer unit tests to ensure test passing when using windows style line separator (\r\n).

### CODE REVIEW

**Comment by schen149** [comment]
@cowchipkid What do you think about this? 

For the "Fr. Zahm" example, I don't think there's a neat fix except adding "Fr" to the known acronym list.

**Comment by Slash0BZ** [comment]
@schen149 I think adding Fr. to the known acronym list is a good way to go. Maybe you can add it here as well?

File: tokenizer/src/main/java/edu/illinois/cs/cogcomp/nlp/tokenizer/TokenizerStateMachine.java [hunk 1]
```diff
@@ -332,9 +332,14 @@ public void process(char token) {
                                 } else {
                                     // check for all uppercase and periods back to the start of the
                                     // word or a "-"
+                                    char nextnextChar = peek(2);
                                     if (getCurrent().isAbbr())
                                         return; // previous was upper case, acronym and word
                                                 // continues
+                                    else if (Character.isWhitespace(c) && Character.isLowerCase(nextnextChar))
```
Comment (Slash0BZ) [inline tokenizer/src/main/java/edu/illinois/cs/cogcomp/nlp/tokenizer/TokenizerStateMachine.java]: I think in this "else" clause, Character.isWhitespace(c) is redundant. Checking nnc to be lowercase looks good to me

**Comment by cowchipkid** [comment]
If "Fr." is a lagitimate acronym, and it is, altho rarely used,  it should definitely be added to the acronyms list, that's the right way to go.

**Comment by danyaljj** [comment]
What is this PR waiting for @schen149 ?

**Comment by schen149** [comment]
Review from @cogcomp-dev ? Or do you want me to run a POS benchmark? @danyaljj
