### PR TITLE
fixed a bug in json serializer.  Also updated to explicitly store and…

### LINKED ISSUE #661: sentence and token views not serialized, but they should be
We have an explicit sentence view: make sure it is written out when serialized, and that it is read when deserialized.  Check deserialization does not create errors.

### PR DESCRIPTION
**Pull request by mssammon**
… read SENTENCE view. Closes #661  and #660

### CODE REVIEW

File: core-utilities/src/main/java/edu/illinois/cs/cogcomp/core/utilities/JsonSerializer.java [hunk 1]
```diff
@@ -435,9 +435,8 @@ JsonObject writeTextAnnotation(TextAnnotation ta, boolean doWriteTokenOffsets) {
 
         JsonArray views = new JsonArray();
         for (String viewName : Sorters.sortSet(ta.getAvailableViews())) {
-            // TODO: comment out this next two lines as part of addressing issue #406
-            if (viewName.equals(ViewNames.SENTENCE))
-                continue;
+//            if (viewName.equals(ViewNames.SENTENCE))
+//                continue;
```
Comment (ChaseDuncan) [inline core-utilities/src/main/java/edu/illinois/cs/cogcomp/core/utilities/JsonSerializer.java]: Why are these being left in as comments?

File: core-utilities/src/main/java/edu/illinois/cs/cogcomp/core/utilities/protobuf/ProtobufSerializer.java [hunk 2]
```diff
@@ -220,8 +220,8 @@ public static TextAnnotationProto writeTextAnnotation(TextAnnotation ta) {
         writeSentences(ta, taBuilder);
 
         for (String viewName : Sorters.sortSet(ta.getAvailableViews())) {
-            if (viewName.equals(ViewNames.SENTENCE))
-                continue;
+//            if (viewName.equals(ViewNames.SENTENCE))
+//                continue;
```
Comment (ChaseDuncan) [inline core-utilities/src/main/java/edu/illinois/cs/cogcomp/core/utilities/protobuf/ProtobufSerializer.java]: Why are these being left in as comments?

Comment (mssammon) [reply core-utilities/src/main/java/edu/illinois/cs/cogcomp/core/utilities/protobuf/ProtobufSerializer.java]: good catch. Removed and pushed changes.
